"""
polymarket_data.py — Auto-generated Polymarket US player prop data.
Fetched: 2026-06-09 01:15 ET
"""

POLYMARKET_MARKETS = [
    # ── ASSISTS ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "assists", "line": 3.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "assists", "line": 4.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "assists", "line": 5.5, "over_price": 0.92},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "assists", "line": 6.5, "over_price": 0.68},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "assists", "line": 3.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "assists", "line": 4.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "assists", "line": 5.5, "over_price": 0.9},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "assists", "line": 6.5, "over_price": 0.65},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 1.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 2.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 3.5, "over_price": 0.9},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 4.5, "over_price": 0.6},
    {"player": "OG Anunoby", "team": "NYK", "stat": "assists", "line": 0.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "assists", "line": 1.5, "over_price": 0.89},
    {"player": "OG Anunoby", "team": "NYK", "stat": "assists", "line": 2.5, "over_price": 0.5},
    {"player": "Stephon Castle", "team": "SAS", "stat": "assists", "line": 4.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "assists", "line": 5.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "assists", "line": 6.5, "over_price": 0.75},
    {"player": "Stephon Castle", "team": "SAS", "stat": "assists", "line": 7.5, "over_price": 0.54},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "assists", "line": 1.5, "over_price": 0.96},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "assists", "line": 2.5, "over_price": 0.93},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "assists", "line": 3.5, "over_price": 0.69},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "assists", "line": 4.5, "over_price": 0.41},
    # ── POINTS ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "points", "line": 14.5, "over_price": 0.94},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "points", "line": 19.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "points", "line": 24.5, "over_price": 0.94},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "points", "line": 19.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "points", "line": 24.5, "over_price": 0.93},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "points", "line": 29.5, "over_price": 0.94},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "points", "line": 34.5, "over_price": 0.93},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "points", "line": 14.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "points", "line": 19.5, "over_price": 0.93},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "points", "line": 24.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "points", "line": 29.5, "over_price": 0.93},
    {"player": "OG Anunoby", "team": "NYK", "stat": "points", "line": 9.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "points", "line": 14.5, "over_price": 0.93},
    {"player": "OG Anunoby", "team": "NYK", "stat": "points", "line": 19.5, "over_price": 0.93},
    {"player": "OG Anunoby", "team": "NYK", "stat": "points", "line": 24.5, "over_price": 0.94},
    {"player": "Stephon Castle", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "points", "line": 14.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "points", "line": 19.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "points", "line": 24.5, "over_price": 0.94},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "points", "line": 24.5, "over_price": 0.96},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "points", "line": 29.5, "over_price": 0.93},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "points", "line": 34.5, "over_price": 0.94},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "points", "line": 39.5, "over_price": 0.94},
    # ── REBOUNDS ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "rebounds", "line": 0.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "rebounds", "line": 2.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "rebounds", "line": 4.5, "over_price": 0.94},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "rebounds", "line": 6.5, "over_price": 0.66},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "rebounds", "line": 1.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "rebounds", "line": 3.5, "over_price": 0.93},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "rebounds", "line": 5.5, "over_price": 0.94},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "rebounds", "line": 8.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "rebounds", "line": 10.5, "over_price": 0.94},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "rebounds", "line": 12.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "rebounds", "line": 14.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 2.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 4.5, "over_price": 0.93},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 6.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 8.5, "over_price": 0.94},
    {"player": "Stephon Castle", "team": "SAS", "stat": "rebounds", "line": 1.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "rebounds", "line": 3.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "rebounds", "line": 5.5, "over_price": 0.94},
    {"player": "Stephon Castle", "team": "SAS", "stat": "rebounds", "line": 7.5, "over_price": 0.94},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "rebounds", "line": 8.5, "over_price": 0.96},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "rebounds", "line": 10.5, "over_price": 0.96},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "rebounds", "line": 12.5, "over_price": 0.94},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "rebounds", "line": 14.5, "over_price": 0.94},
    # ── THREES ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "threes", "line": 1.5, "over_price": 0.94},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "threes", "line": 2.5, "over_price": 0.93},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "threes", "line": 1.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "threes", "line": 2.5, "over_price": 0.94},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "threes", "line": 3.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "threes", "line": 1.5, "over_price": 0.93},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "threes", "line": 2.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "threes", "line": 1.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "threes", "line": 2.5, "over_price": 0.93},
    {"player": "OG Anunoby", "team": "NYK", "stat": "threes", "line": 3.5, "over_price": 0.93},
    {"player": "Stephon Castle", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "Stephon Castle", "team": "SAS", "stat": "threes", "line": 1.5, "over_price": 0.93},
    {"player": "Stephon Castle", "team": "SAS", "stat": "threes", "line": 2.5, "over_price": 0.95},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "threes", "line": 1.5, "over_price": 0.94},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "threes", "line": 2.5, "over_price": 0.94},
]
