"""
polymarket_data.py — Auto-generated Polymarket US player prop data.
Fetched: 2026-06-06 23:04 ET
"""

POLYMARKET_MARKETS = [
    # ── ASSISTS ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "assists", "line": 3.5, "over_price": 0.83},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "assists", "line": 4.5, "over_price": 0.71},
    {"player": "Devin Vassell", "team": "SAS", "stat": "assists", "line": 1.5, "over_price": 0.75},
    {"player": "Dylan Harper", "team": "SAS", "stat": "assists", "line": 1.5, "over_price": 0.87},
    {"player": "Dylan Harper", "team": "SAS", "stat": "assists", "line": 2.5, "over_price": 0.66},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "assists", "line": 4.5, "over_price": 0.77},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "assists", "line": 5.5, "over_price": 0.58},
    {"player": "Josh Hart", "team": "NYK", "stat": "assists", "line": 2.5, "over_price": 0.86},
    {"player": "Josh Hart", "team": "NYK", "stat": "assists", "line": 3.5, "over_price": 0.66},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 1.5, "over_price": 0.95},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 2.5, "over_price": 0.82},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "assists", "line": 3.5, "over_price": 0.6},
    {"player": "Mikal Bridges", "team": "NYK", "stat": "assists", "line": 1.5, "over_price": 0.87},
    {"player": "Mikal Bridges", "team": "NYK", "stat": "assists", "line": 2.5, "over_price": 0.65},
    {"player": "OG Anunoby", "team": "NYK", "stat": "assists", "line": 0.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "assists", "line": 1.5, "over_price": 0.81},
    {"player": "Stephon Castle", "team": "SAS", "stat": "assists", "line": 4.5, "over_price": 0.84},
    {"player": "Stephon Castle", "team": "SAS", "stat": "assists", "line": 5.5, "over_price": 0.66},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "assists", "line": 1.5, "over_price": 0.86},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "assists", "line": 2.5, "over_price": 0.67},
    # ── POINTS ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.86},
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "points", "line": 14.5, "over_price": 0.56},
    {"player": "Devin Vassell", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.78},
    {"player": "Dylan Harper", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.79},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "points", "line": 19.5, "over_price": 0.83},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "points", "line": 24.5, "over_price": 0.6},
    {"player": "Josh Hart", "team": "NYK", "stat": "points", "line": 4.5, "over_price": 0.89},
    {"player": "Julian Champagnie", "team": "SAS", "stat": "points", "line": 4.5, "over_price": 0.96},
    {"player": "Julian Champagnie", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.56},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "points", "line": 14.5, "over_price": 0.76},
    {"player": "Keldon Johnson", "team": "SAS", "stat": "points", "line": 4.5, "over_price": 0.63},
    {"player": "Landry Shamet", "team": "NYK", "stat": "points", "line": 4.5, "over_price": 0.85},
    {"player": "Mikal Bridges", "team": "NYK", "stat": "points", "line": 9.5, "over_price": 0.77},
    {"player": "Miles McBride", "team": "NYK", "stat": "points", "line": 4.5, "over_price": 0.67},
    {"player": "OG Anunoby", "team": "NYK", "stat": "points", "line": 9.5, "over_price": 0.91},
    {"player": "OG Anunoby", "team": "NYK", "stat": "points", "line": 14.5, "over_price": 0.59},
    {"player": "Stephon Castle", "team": "SAS", "stat": "points", "line": 9.5, "over_price": 0.89},
    {"player": "Stephon Castle", "team": "SAS", "stat": "points", "line": 14.5, "over_price": 0.61},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "points", "line": 19.5, "over_price": 0.87},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "points", "line": 24.5, "over_price": 0.67},
    # ── REBOUNDS ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "rebounds", "line": 2.5, "over_price": 0.69},
    {"player": "Devin Vassell", "team": "SAS", "stat": "rebounds", "line": 3.5, "over_price": 0.77},
    {"player": "Dylan Harper", "team": "SAS", "stat": "rebounds", "line": 2.5, "over_price": 0.93},
    {"player": "Dylan Harper", "team": "SAS", "stat": "rebounds", "line": 4.5, "over_price": 0.68},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "rebounds", "line": 2.5, "over_price": 0.65},
    {"player": "Josh Hart", "team": "NYK", "stat": "rebounds", "line": 4.5, "over_price": 0.93},
    {"player": "Josh Hart", "team": "NYK", "stat": "rebounds", "line": 6.5, "over_price": 0.74},
    {"player": "Julian Champagnie", "team": "SAS", "stat": "rebounds", "line": 2.5, "over_price": 0.93},
    {"player": "Julian Champagnie", "team": "SAS", "stat": "rebounds", "line": 4.5, "over_price": 0.69},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "rebounds", "line": 8.5, "over_price": 0.83},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "rebounds", "line": 10.5, "over_price": 0.62},
    {"player": "Keldon Johnson", "team": "SAS", "stat": "rebounds", "line": 1.5, "over_price": 0.77},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 2.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 4.5, "over_price": 0.96},
    {"player": "OG Anunoby", "team": "NYK", "stat": "rebounds", "line": 6.5, "over_price": 0.93},
    {"player": "Stephon Castle", "team": "SAS", "stat": "rebounds", "line": 3.5, "over_price": 0.79},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "rebounds", "line": 8.5, "over_price": 0.85},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "rebounds", "line": 10.5, "over_price": 0.67},
    # ── THREES ────────────────────────────────────────
    {"player": "De'Aaron Fox", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.81},
    {"player": "Devin Vassell", "team": "SAS", "stat": "threes", "line": 1.5, "over_price": 0.76},
    {"player": "Dylan Harper", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.67},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.96},
    {"player": "Jalen Brunson", "team": "NYK", "stat": "threes", "line": 1.5, "over_price": 0.73},
    {"player": "Josh Hart", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.78},
    {"player": "Julian Champagnie", "team": "SAS", "stat": "threes", "line": 1.5, "over_price": 0.76},
    {"player": "Karl-Anthony Towns", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.82},
    {"player": "Landry Shamet", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.87},
    {"player": "Landry Shamet", "team": "NYK", "stat": "threes", "line": 1.5, "over_price": 0.59},
    {"player": "Mikal Bridges", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.81},
    {"player": "Miles McBride", "team": "NYK", "stat": "threes", "line": 0.5, "over_price": 0.77},
    {"player": "Stephon Castle", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.8},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "threes", "line": 0.5, "over_price": 0.93},
    {"player": "Victor Wembanyama", "team": "SAS", "stat": "threes", "line": 1.5, "over_price": 0.66},
]
